version: '3'

services:
  web:
    container_name: web
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:14-alpine
